"""Add is_trashed column to notes

Revision ID: 6bcfd7f15b38
Revises: a678bbfcdd1a
Create Date: 2025-03-20 19:45:52.553673

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6bcfd7f15b38'
down_revision = 'a678bbfcdd1a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('note', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_trashed', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('trashed_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('note', schema=None) as batch_op:
        batch_op.drop_column('trashed_at')
        batch_op.drop_column('is_trashed')

    # ### end Alembic commands ###
